/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGD
#define SWIGD
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>

/* Contract support. */
#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_DSetPendingException(SWIG_DException, msg); return nullreturn; } else


// Support for throwing D exceptions from C/C++.
typedef enum {
  SWIG_DException = 0,
  SWIG_DIllegalArgumentException,
  SWIG_DIllegalElementException,
  SWIG_DIOException,
  SWIG_DNoSuchElementException
} SWIG_DExceptionCodes;

typedef void (* SWIG_DExceptionCallback_t)(const char *);

typedef struct {
  SWIG_DExceptionCodes code;
  SWIG_DExceptionCallback_t callback;
} SWIG_DException_t;

static SWIG_DException_t SWIG_d_exceptions[] = {
  { SWIG_DException, NULL },
  { SWIG_DIllegalArgumentException, NULL },
  { SWIG_DIllegalElementException, NULL },
  { SWIG_DIOException, NULL },
  { SWIG_DNoSuchElementException, NULL }
};

static void SWIGUNUSED SWIG_DSetPendingException(SWIG_DExceptionCodes code, const char *msg) {
  if ((size_t)code < sizeof(SWIG_d_exceptions)/sizeof(SWIG_DException_t)) {
    SWIG_d_exceptions[code].callback(msg);
  } else {
    SWIG_d_exceptions[SWIG_DException].callback(msg);
  }
}

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT void SWIGRegisterExceptionCallbacks_mad(
  SWIG_DExceptionCallback_t exceptionCallback,
  SWIG_DExceptionCallback_t illegalArgumentCallback,
  SWIG_DExceptionCallback_t illegalElementCallback,
  SWIG_DExceptionCallback_t ioCallback,
  SWIG_DExceptionCallback_t noSuchElementCallback) {
  SWIG_d_exceptions[SWIG_DException].callback = exceptionCallback;
  SWIG_d_exceptions[SWIG_DIllegalArgumentException].callback = illegalArgumentCallback;
  SWIG_d_exceptions[SWIG_DIllegalElementException].callback = illegalElementCallback;
  SWIG_d_exceptions[SWIG_DIOException].callback = ioCallback;
  SWIG_d_exceptions[SWIG_DNoSuchElementException].callback = noSuchElementCallback;
}


// Callback for returning strings to D without leaking memory.
typedef char * (* SWIG_DStringHelperCallback)(const char *);
static SWIG_DStringHelperCallback SWIG_d_string_callback = NULL;

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT void SWIGRegisterStringCallback_mad(SWIG_DStringHelperCallback callback) {
  SWIG_d_string_callback = callback;
}


#include <mad.h>

typedef struct {
  long pid;
  int in;
  int out;
} mad_decoder_async;

typedef struct {
  struct mad_stream stream;
  struct mad_frame frame;
  struct mad_synth synth;
} mad_decoder_sync;


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT int D_SIZEOF_INT_get() {
  int jresult ;
  int result;
  
  result = (int)(4);
  jresult = result;
  return jresult;
}


SWIGEXPORT int D_SIZEOF_LONG_get() {
  int jresult ;
  int result;
  
  result = (int)(8);
  jresult = result;
  return jresult;
}


SWIGEXPORT int D_SIZEOF_LONG_LONG_get() {
  int jresult ;
  int result;
  
  result = (int)(8);
  jresult = result;
  return jresult;
}


SWIGEXPORT int D_MAD_VERSION_MAJOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result;
  return jresult;
}


SWIGEXPORT int D_MAD_VERSION_MINOR_get() {
  int jresult ;
  int result;
  
  result = (int)(15);
  jresult = result;
  return jresult;
}


SWIGEXPORT int D_MAD_VERSION_PATCH_get() {
  int jresult ;
  int result;
  
  result = (int)(1);
  jresult = result;
  return jresult;
}


SWIGEXPORT char * D_MAD_VERSION_EXTRA_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)(" (beta)");
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_MAD_VERSION_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)("0.15.1 (beta)");
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_MAD_PUBLISHYEAR_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)("2000-2004");
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_MAD_AUTHOR_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)("Underbit Technologies, Inc.");
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_MAD_EMAIL_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)("info@underbit.com");
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_mad_version_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)(char *)mad_version;
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_mad_copyright_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)(char *)mad_copyright;
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_mad_author_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)(char *)mad_author;
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_mad_build_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)(char *)mad_build;
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int D_MAD_F_FRACBITS_get() {
  int jresult ;
  int result;
  
  result = (int)(28);
  jresult = result;
  return jresult;
}


SWIGEXPORT int D_MAD_F_SCALEBITS_get() {
  int jresult ;
  int result;
  
  result = (int)(28);
  jresult = result;
  return jresult;
}


SWIGEXPORT int D_mad_f_abs(int jarg1) {
  int jresult ;
  mad_fixed_t arg1 ;
  mad_fixed_t result;
  
  arg1 = (mad_fixed_t)jarg1;
  result = (mad_fixed_t)mad_f_abs(arg1);
  jresult = result;
  return jresult;
}


SWIGEXPORT int D_mad_f_div(int jarg1, int jarg2) {
  int jresult ;
  mad_fixed_t arg1 ;
  mad_fixed_t arg2 ;
  mad_fixed_t result;
  
  arg1 = (mad_fixed_t)jarg1;
  arg2 = (mad_fixed_t)jarg2;
  result = (mad_fixed_t)mad_f_div(arg1,arg2);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_bitptr__byte_set(void * jarg1, void * jarg2) {
  struct mad_bitptr *arg1 = (struct mad_bitptr *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  
  arg1 = (struct mad_bitptr *)jarg1;
  arg2 = (unsigned char *)jarg2;
  if (arg1) (arg1)->byte = (unsigned char const *)arg2;
}


SWIGEXPORT void * D_mad_bitptr__byte_get(void * jarg1) {
  void * jresult ;
  struct mad_bitptr *arg1 = (struct mad_bitptr *) 0 ;
  unsigned char *result = 0 ;
  
  arg1 = (struct mad_bitptr *)jarg1;
  result = (unsigned char *) ((arg1)->byte);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_bitptr_cache_set(void * jarg1, unsigned short jarg2) {
  struct mad_bitptr *arg1 = (struct mad_bitptr *) 0 ;
  unsigned short arg2 ;
  
  arg1 = (struct mad_bitptr *)jarg1;
  arg2 = (unsigned short)jarg2;
  if (arg1) (arg1)->cache = arg2;
}


SWIGEXPORT unsigned short D_mad_bitptr_cache_get(void * jarg1) {
  unsigned short jresult ;
  struct mad_bitptr *arg1 = (struct mad_bitptr *) 0 ;
  unsigned short result;
  
  arg1 = (struct mad_bitptr *)jarg1;
  result = (unsigned short) ((arg1)->cache);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_bitptr_left_set(void * jarg1, unsigned short jarg2) {
  struct mad_bitptr *arg1 = (struct mad_bitptr *) 0 ;
  unsigned short arg2 ;
  
  arg1 = (struct mad_bitptr *)jarg1;
  arg2 = (unsigned short)jarg2;
  if (arg1) (arg1)->left = arg2;
}


SWIGEXPORT unsigned short D_mad_bitptr_left_get(void * jarg1) {
  unsigned short jresult ;
  struct mad_bitptr *arg1 = (struct mad_bitptr *) 0 ;
  unsigned short result;
  
  arg1 = (struct mad_bitptr *)jarg1;
  result = (unsigned short) ((arg1)->left);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_mad_bitptr() {
  void * jresult ;
  struct mad_bitptr *result = 0 ;
  
  result = (struct mad_bitptr *)calloc(1, sizeof(struct mad_bitptr));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_mad_bitptr(void * jarg1) {
  struct mad_bitptr *arg1 = (struct mad_bitptr *) 0 ;
  
  arg1 = (struct mad_bitptr *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_mad_bit_init(void * jarg1, void * jarg2) {
  struct mad_bitptr *arg1 = (struct mad_bitptr *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  
  arg1 = (struct mad_bitptr *)jarg1;
  arg2 = (unsigned char *)jarg2;
  mad_bit_init(arg1,(unsigned char const *)arg2);
}


SWIGEXPORT unsigned int D_mad_bit_length(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  struct mad_bitptr *arg1 = (struct mad_bitptr *) 0 ;
  struct mad_bitptr *arg2 = (struct mad_bitptr *) 0 ;
  unsigned int result;
  
  arg1 = (struct mad_bitptr *)jarg1;
  arg2 = (struct mad_bitptr *)jarg2;
  result = (unsigned int)mad_bit_length((struct mad_bitptr const *)arg1,(struct mad_bitptr const *)arg2);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_mad_bit_nextbyte(void * jarg1) {
  void * jresult ;
  struct mad_bitptr *arg1 = (struct mad_bitptr *) 0 ;
  unsigned char *result = 0 ;
  
  arg1 = (struct mad_bitptr *)jarg1;
  result = (unsigned char *)mad_bit_nextbyte((struct mad_bitptr const *)arg1);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_bit_skip(void * jarg1, unsigned int jarg2) {
  struct mad_bitptr *arg1 = (struct mad_bitptr *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct mad_bitptr *)jarg1;
  arg2 = (unsigned int)jarg2;
  mad_bit_skip(arg1,arg2);
}


SWIGEXPORT unsigned long D_mad_bit_read(void * jarg1, unsigned int jarg2) {
  unsigned long jresult ;
  struct mad_bitptr *arg1 = (struct mad_bitptr *) 0 ;
  unsigned int arg2 ;
  unsigned long result;
  
  arg1 = (struct mad_bitptr *)jarg1;
  arg2 = (unsigned int)jarg2;
  result = (unsigned long)mad_bit_read(arg1,arg2);
  jresult = (unsigned long)result;
  return jresult;
}


SWIGEXPORT unsigned short D_mad_bit_crc(void * jarg1, unsigned int jarg2, unsigned short jarg3) {
  unsigned short jresult ;
  struct mad_bitptr arg1 ;
  unsigned int arg2 ;
  unsigned short arg3 ;
  struct mad_bitptr *argp1 ;
  unsigned short result;
  
  argp1 = (struct mad_bitptr *)jarg1;
  if (!argp1) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null struct mad_bitptr");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (unsigned int)jarg2;
  arg3 = (unsigned short)jarg3;
  result = (unsigned short)mad_bit_crc(arg1,arg2,arg3);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_timer_t_seconds_set(void * jarg1, long jarg2) {
  mad_timer_t *arg1 = (mad_timer_t *) 0 ;
  long arg2 ;
  
  arg1 = (mad_timer_t *)jarg1;
  arg2 = (long)jarg2;
  if (arg1) (arg1)->seconds = arg2;
}


SWIGEXPORT long D_mad_timer_t_seconds_get(void * jarg1) {
  long jresult ;
  mad_timer_t *arg1 = (mad_timer_t *) 0 ;
  long result;
  
  arg1 = (mad_timer_t *)jarg1;
  result = (long) ((arg1)->seconds);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_timer_t_fraction_set(void * jarg1, unsigned long jarg2) {
  mad_timer_t *arg1 = (mad_timer_t *) 0 ;
  unsigned long arg2 ;
  
  arg1 = (mad_timer_t *)jarg1;
  arg2 = (unsigned long)jarg2;
  if (arg1) (arg1)->fraction = arg2;
}


SWIGEXPORT unsigned long D_mad_timer_t_fraction_get(void * jarg1) {
  unsigned long jresult ;
  mad_timer_t *arg1 = (mad_timer_t *) 0 ;
  unsigned long result;
  
  arg1 = (mad_timer_t *)jarg1;
  result = (unsigned long) ((arg1)->fraction);
  jresult = (unsigned long)result;
  return jresult;
}


SWIGEXPORT void * D_new_mad_timer_t() {
  void * jresult ;
  mad_timer_t *result = 0 ;
  
  result = (mad_timer_t *)calloc(1, sizeof(mad_timer_t));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_mad_timer_t(void * jarg1) {
  mad_timer_t *arg1 = (mad_timer_t *) 0 ;
  
  arg1 = (mad_timer_t *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void * D_mad_timer_zero_get() {
  void * jresult ;
  mad_timer_t *result = 0 ;
  
  result = (mad_timer_t *)&mad_timer_zero;
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT unsigned long D_MAD_TIMER_RESOLUTION_get() {
  unsigned long jresult ;
  unsigned long result;
  
  result = (unsigned long)(352800000UL);
  jresult = (unsigned long)result;
  return jresult;
}


SWIGEXPORT int D_mad_timer_compare(void * jarg1, void * jarg2) {
  int jresult ;
  mad_timer_t arg1 ;
  mad_timer_t arg2 ;
  mad_timer_t *argp1 ;
  mad_timer_t *argp2 ;
  int result;
  
  argp1 = (mad_timer_t *)jarg1;
  if (!argp1) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null mad_timer_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = (mad_timer_t *)jarg2;
  if (!argp2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null mad_timer_t");
    return 0;
  }
  arg2 = *argp2; 
  result = (int)mad_timer_compare(arg1,arg2);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_timer_negate(void * jarg1) {
  mad_timer_t *arg1 = (mad_timer_t *) 0 ;
  
  arg1 = (mad_timer_t *)jarg1;
  mad_timer_negate(arg1);
}


SWIGEXPORT void * D_mad_timer_abs(void * jarg1) {
  void * jresult ;
  mad_timer_t arg1 ;
  mad_timer_t *argp1 ;
  mad_timer_t result;
  
  argp1 = (mad_timer_t *)jarg1;
  if (!argp1) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null mad_timer_t");
    return 0;
  }
  arg1 = *argp1; 
  result = mad_timer_abs(arg1);
  {
    mad_timer_t * resultptr = (mad_timer_t *) malloc(sizeof(mad_timer_t));
    memmove(resultptr, &result, sizeof(mad_timer_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void D_mad_timer_set(void * jarg1, unsigned long jarg2, unsigned long jarg3, unsigned long jarg4) {
  mad_timer_t *arg1 = (mad_timer_t *) 0 ;
  unsigned long arg2 ;
  unsigned long arg3 ;
  unsigned long arg4 ;
  
  arg1 = (mad_timer_t *)jarg1;
  arg2 = (unsigned long)jarg2;
  arg3 = (unsigned long)jarg3;
  arg4 = (unsigned long)jarg4;
  mad_timer_set(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void D_mad_timer_add(void * jarg1, void * jarg2) {
  mad_timer_t *arg1 = (mad_timer_t *) 0 ;
  mad_timer_t arg2 ;
  mad_timer_t *argp2 ;
  
  arg1 = (mad_timer_t *)jarg1;
  argp2 = (mad_timer_t *)jarg2;
  if (!argp2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null mad_timer_t");
    return ;
  }
  arg2 = *argp2; 
  mad_timer_add(arg1,arg2);
}


SWIGEXPORT void D_mad_timer_multiply(void * jarg1, long jarg2) {
  mad_timer_t *arg1 = (mad_timer_t *) 0 ;
  long arg2 ;
  
  arg1 = (mad_timer_t *)jarg1;
  arg2 = (long)jarg2;
  mad_timer_multiply(arg1,arg2);
}


SWIGEXPORT long D_mad_timer_count(void * jarg1, int jarg2) {
  long jresult ;
  mad_timer_t arg1 ;
  enum mad_units arg2 ;
  mad_timer_t *argp1 ;
  long result;
  
  argp1 = (mad_timer_t *)jarg1;
  if (!argp1) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null mad_timer_t");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (enum mad_units)jarg2; 
  result = (long)mad_timer_count(arg1,arg2);
  jresult = result;
  return jresult;
}


SWIGEXPORT unsigned long D_mad_timer_fraction(void * jarg1, unsigned long jarg2) {
  unsigned long jresult ;
  mad_timer_t arg1 ;
  unsigned long arg2 ;
  mad_timer_t *argp1 ;
  unsigned long result;
  
  argp1 = (mad_timer_t *)jarg1;
  if (!argp1) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null mad_timer_t");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (unsigned long)jarg2;
  result = (unsigned long)mad_timer_fraction(arg1,arg2);
  jresult = (unsigned long)result;
  return jresult;
}


SWIGEXPORT void D_mad_timer_string(void * jarg1, char * jarg2, char * jarg3, int jarg4, int jarg5, unsigned long jarg6) {
  mad_timer_t arg1 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  enum mad_units arg4 ;
  enum mad_units arg5 ;
  unsigned long arg6 ;
  mad_timer_t *argp1 ;
  
  argp1 = (mad_timer_t *)jarg1;
  if (!argp1) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null mad_timer_t");
    return ;
  }
  arg1 = *argp1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  arg4 = (enum mad_units)jarg4; 
  arg5 = (enum mad_units)jarg5; 
  arg6 = (unsigned long)jarg6;
  mad_timer_string(arg1,arg2,(char const *)arg3,arg4,arg5,arg6);
}


SWIGEXPORT int D_MAD_BUFFER_GUARD_get() {
  int jresult ;
  int result;
  
  result = (int)(8);
  jresult = result;
  return jresult;
}


SWIGEXPORT int D_MAD_BUFFER_MDLEN_get() {
  int jresult ;
  int result;
  
  result = (int)((511+2048+8));
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_buffer_set(void * jarg1, void * jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (unsigned char *)jarg2;
  if (arg1) (arg1)->buffer = (unsigned char const *)arg2;
}


SWIGEXPORT void * D_mad_stream_buffer_get(void * jarg1) {
  void * jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned char *result = 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (unsigned char *) ((arg1)->buffer);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_bufend_set(void * jarg1, void * jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (unsigned char *)jarg2;
  if (arg1) (arg1)->bufend = (unsigned char const *)arg2;
}


SWIGEXPORT void * D_mad_stream_bufend_get(void * jarg1) {
  void * jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned char *result = 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (unsigned char *) ((arg1)->bufend);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_skiplen_set(void * jarg1, unsigned long jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned long arg2 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (unsigned long)jarg2;
  if (arg1) (arg1)->skiplen = arg2;
}


SWIGEXPORT unsigned long D_mad_stream_skiplen_get(void * jarg1) {
  unsigned long jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned long result;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (unsigned long) ((arg1)->skiplen);
  jresult = (unsigned long)result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_sync_set(void * jarg1, int jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  int arg2 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->sync = arg2;
}


SWIGEXPORT int D_mad_stream_sync_get(void * jarg1) {
  int jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  int result;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (int) ((arg1)->sync);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_freerate_set(void * jarg1, unsigned long jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned long arg2 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (unsigned long)jarg2;
  if (arg1) (arg1)->freerate = arg2;
}


SWIGEXPORT unsigned long D_mad_stream_freerate_get(void * jarg1) {
  unsigned long jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned long result;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (unsigned long) ((arg1)->freerate);
  jresult = (unsigned long)result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_this_frame_set(void * jarg1, void * jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (unsigned char *)jarg2;
  if (arg1) (arg1)->this_frame = (unsigned char const *)arg2;
}


SWIGEXPORT void * D_mad_stream_this_frame_get(void * jarg1) {
  void * jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned char *result = 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (unsigned char *) ((arg1)->this_frame);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_next_frame_set(void * jarg1, void * jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (unsigned char *)jarg2;
  if (arg1) (arg1)->next_frame = (unsigned char const *)arg2;
}


SWIGEXPORT void * D_mad_stream_next_frame_get(void * jarg1) {
  void * jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned char *result = 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (unsigned char *) ((arg1)->next_frame);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_ptr_set(void * jarg1, void * jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  struct mad_bitptr *arg2 = (struct mad_bitptr *) 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (struct mad_bitptr *)jarg2;
  if (arg1) (arg1)->ptr = *arg2;
}


SWIGEXPORT void * D_mad_stream_ptr_get(void * jarg1) {
  void * jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  struct mad_bitptr *result = 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (struct mad_bitptr *)& ((arg1)->ptr);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_anc_ptr_set(void * jarg1, void * jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  struct mad_bitptr *arg2 = (struct mad_bitptr *) 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (struct mad_bitptr *)jarg2;
  if (arg1) (arg1)->anc_ptr = *arg2;
}


SWIGEXPORT void * D_mad_stream_anc_ptr_get(void * jarg1) {
  void * jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  struct mad_bitptr *result = 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (struct mad_bitptr *)& ((arg1)->anc_ptr);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_anc_bitlen_set(void * jarg1, unsigned int jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (unsigned int)jarg2;
  if (arg1) (arg1)->anc_bitlen = arg2;
}


SWIGEXPORT unsigned int D_mad_stream_anc_bitlen_get(void * jarg1) {
  unsigned int jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned int result;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (unsigned int) ((arg1)->anc_bitlen);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_main_data_set(void * jarg1, void * jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned char (*arg2)[(511+2048+8)] = (unsigned char (*)[(511+2048+8)]) 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (unsigned char (*)[(511+2048+8)])jarg2;
  if (arg1) (arg1)->main_data = (unsigned char (*)[(511+2048+8)])arg2;
}


SWIGEXPORT void * D_mad_stream_main_data_get(void * jarg1) {
  void * jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned char (*result)[(511+2048+8)] = 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (unsigned char (*)[(511+2048+8)]) ((arg1)->main_data);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_md_len_set(void * jarg1, unsigned int jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (unsigned int)jarg2;
  if (arg1) (arg1)->md_len = arg2;
}


SWIGEXPORT unsigned int D_mad_stream_md_len_get(void * jarg1) {
  unsigned int jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned int result;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (unsigned int) ((arg1)->md_len);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_options_set(void * jarg1, int jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  int arg2 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->options = arg2;
}


SWIGEXPORT int D_mad_stream_options_get(void * jarg1) {
  int jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  int result;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (int) ((arg1)->options);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_stream_error_set(void * jarg1, int jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  enum mad_error arg2 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (enum mad_error)jarg2; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT int D_mad_stream_error_get(void * jarg1) {
  int jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  enum mad_error result;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (enum mad_error) ((arg1)->error);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void * D_new_mad_stream() {
  void * jresult ;
  struct mad_stream *result = 0 ;
  
  result = (struct mad_stream *)calloc(1, sizeof(struct mad_stream));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_mad_stream(void * jarg1) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_mad_stream_init(void * jarg1) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  mad_stream_init(arg1);
}


SWIGEXPORT void D_mad_stream_finish(void * jarg1) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  mad_stream_finish(arg1);
}


SWIGEXPORT void D_mad_stream_buffer(void * jarg1, void * jarg2, unsigned long jarg3) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned long arg3 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (unsigned char *)jarg2;
  arg3 = (unsigned long)jarg3;
  mad_stream_buffer(arg1,(unsigned char const *)arg2,arg3);
}


SWIGEXPORT void D_mad_stream_skip(void * jarg1, unsigned long jarg2) {
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  unsigned long arg2 ;
  
  arg1 = (struct mad_stream *)jarg1;
  arg2 = (unsigned long)jarg2;
  mad_stream_skip(arg1,arg2);
}


SWIGEXPORT int D_mad_stream_sync(void * jarg1) {
  int jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  int result;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (int)mad_stream_sync(arg1);
  jresult = result;
  return jresult;
}


SWIGEXPORT char * D_mad_stream_errorstr(void * jarg1) {
  char * jresult ;
  struct mad_stream *arg1 = (struct mad_stream *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct mad_stream *)jarg1;
  result = (char *)mad_stream_errorstr((struct mad_stream const *)arg1);
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void D_mad_header_layer_set(void * jarg1, int jarg2) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  enum mad_layer arg2 ;
  
  arg1 = (struct mad_header *)jarg1;
  arg2 = (enum mad_layer)jarg2; 
  if (arg1) (arg1)->layer = arg2;
}


SWIGEXPORT int D_mad_header_layer_get(void * jarg1) {
  int jresult ;
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  enum mad_layer result;
  
  arg1 = (struct mad_header *)jarg1;
  result = (enum mad_layer) ((arg1)->layer);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void D_mad_header_mode_set(void * jarg1, int jarg2) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  enum mad_mode arg2 ;
  
  arg1 = (struct mad_header *)jarg1;
  arg2 = (enum mad_mode)jarg2; 
  if (arg1) (arg1)->mode = arg2;
}


SWIGEXPORT int D_mad_header_mode_get(void * jarg1) {
  int jresult ;
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  enum mad_mode result;
  
  arg1 = (struct mad_header *)jarg1;
  result = (enum mad_mode) ((arg1)->mode);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void D_mad_header_mode_extension_set(void * jarg1, int jarg2) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  int arg2 ;
  
  arg1 = (struct mad_header *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->mode_extension = arg2;
}


SWIGEXPORT int D_mad_header_mode_extension_get(void * jarg1) {
  int jresult ;
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  int result;
  
  arg1 = (struct mad_header *)jarg1;
  result = (int) ((arg1)->mode_extension);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_header_emphasis_set(void * jarg1, int jarg2) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  enum mad_emphasis arg2 ;
  
  arg1 = (struct mad_header *)jarg1;
  arg2 = (enum mad_emphasis)jarg2; 
  if (arg1) (arg1)->emphasis = arg2;
}


SWIGEXPORT int D_mad_header_emphasis_get(void * jarg1) {
  int jresult ;
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  enum mad_emphasis result;
  
  arg1 = (struct mad_header *)jarg1;
  result = (enum mad_emphasis) ((arg1)->emphasis);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void D_mad_header_bitrate_set(void * jarg1, unsigned long jarg2) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  unsigned long arg2 ;
  
  arg1 = (struct mad_header *)jarg1;
  arg2 = (unsigned long)jarg2;
  if (arg1) (arg1)->bitrate = arg2;
}


SWIGEXPORT unsigned long D_mad_header_bitrate_get(void * jarg1) {
  unsigned long jresult ;
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  unsigned long result;
  
  arg1 = (struct mad_header *)jarg1;
  result = (unsigned long) ((arg1)->bitrate);
  jresult = (unsigned long)result;
  return jresult;
}


SWIGEXPORT void D_mad_header_samplerate_set(void * jarg1, unsigned int jarg2) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct mad_header *)jarg1;
  arg2 = (unsigned int)jarg2;
  if (arg1) (arg1)->samplerate = arg2;
}


SWIGEXPORT unsigned int D_mad_header_samplerate_get(void * jarg1) {
  unsigned int jresult ;
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  unsigned int result;
  
  arg1 = (struct mad_header *)jarg1;
  result = (unsigned int) ((arg1)->samplerate);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_header_crc_check_set(void * jarg1, unsigned short jarg2) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  unsigned short arg2 ;
  
  arg1 = (struct mad_header *)jarg1;
  arg2 = (unsigned short)jarg2;
  if (arg1) (arg1)->crc_check = arg2;
}


SWIGEXPORT unsigned short D_mad_header_crc_check_get(void * jarg1) {
  unsigned short jresult ;
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  unsigned short result;
  
  arg1 = (struct mad_header *)jarg1;
  result = (unsigned short) ((arg1)->crc_check);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_header_crc_target_set(void * jarg1, unsigned short jarg2) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  unsigned short arg2 ;
  
  arg1 = (struct mad_header *)jarg1;
  arg2 = (unsigned short)jarg2;
  if (arg1) (arg1)->crc_target = arg2;
}


SWIGEXPORT unsigned short D_mad_header_crc_target_get(void * jarg1) {
  unsigned short jresult ;
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  unsigned short result;
  
  arg1 = (struct mad_header *)jarg1;
  result = (unsigned short) ((arg1)->crc_target);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_header_flags_set(void * jarg1, int jarg2) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  int arg2 ;
  
  arg1 = (struct mad_header *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->flags = arg2;
}


SWIGEXPORT int D_mad_header_flags_get(void * jarg1) {
  int jresult ;
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  int result;
  
  arg1 = (struct mad_header *)jarg1;
  result = (int) ((arg1)->flags);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_header_private_bits_set(void * jarg1, int jarg2) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  int arg2 ;
  
  arg1 = (struct mad_header *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->private_bits = arg2;
}


SWIGEXPORT int D_mad_header_private_bits_get(void * jarg1) {
  int jresult ;
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  int result;
  
  arg1 = (struct mad_header *)jarg1;
  result = (int) ((arg1)->private_bits);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_header_duration_set(void * jarg1, void * jarg2) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  mad_timer_t *arg2 = (mad_timer_t *) 0 ;
  
  arg1 = (struct mad_header *)jarg1;
  arg2 = (mad_timer_t *)jarg2;
  if (arg1) (arg1)->duration = *arg2;
}


SWIGEXPORT void * D_mad_header_duration_get(void * jarg1) {
  void * jresult ;
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  mad_timer_t *result = 0 ;
  
  arg1 = (struct mad_header *)jarg1;
  result = (mad_timer_t *)& ((arg1)->duration);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_mad_header() {
  void * jresult ;
  struct mad_header *result = 0 ;
  
  result = (struct mad_header *)calloc(1, sizeof(struct mad_header));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_mad_header(void * jarg1) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  
  arg1 = (struct mad_header *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_mad_frame_header_set(void * jarg1, void * jarg2) {
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  struct mad_header *arg2 = (struct mad_header *) 0 ;
  
  arg1 = (struct mad_frame *)jarg1;
  arg2 = (struct mad_header *)jarg2;
  if (arg1) (arg1)->header = *arg2;
}


SWIGEXPORT void * D_mad_frame_header_get(void * jarg1) {
  void * jresult ;
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  struct mad_header *result = 0 ;
  
  arg1 = (struct mad_frame *)jarg1;
  result = (struct mad_header *)& ((arg1)->header);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_frame_options_set(void * jarg1, int jarg2) {
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  int arg2 ;
  
  arg1 = (struct mad_frame *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->options = arg2;
}


SWIGEXPORT int D_mad_frame_options_get(void * jarg1) {
  int jresult ;
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  int result;
  
  arg1 = (struct mad_frame *)jarg1;
  result = (int) ((arg1)->options);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_frame_sbsample_set(void * jarg1, void * jarg2) {
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  mad_fixed_t (*arg2)[36][32] ;
  
  arg1 = (struct mad_frame *)jarg1;
  arg2 = (mad_fixed_t (*)[36][32])jarg2; 
  {
    mad_fixed_t (*inp)[36] = (mad_fixed_t (*)[36])(arg2);
    mad_fixed_t (*dest)[36] = (mad_fixed_t (*)[36])(arg1->sbsample);
    size_t ii = 0;
    for (; ii < 2; ++ii) {
      mad_fixed_t *ip = inp[ii];
      mad_fixed_t *dp = dest[ii];
      size_t jj = 0;
      for (; jj < 36; ++jj) dp[jj] = ip[jj];
    }
  }
}


SWIGEXPORT void * D_mad_frame_sbsample_get(void * jarg1) {
  void * jresult ;
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  mad_fixed_t (*result)[36][32] = 0 ;
  
  arg1 = (struct mad_frame *)jarg1;
  result = (mad_fixed_t (*)[36][32])(mad_fixed_t (*)[36][32]) ((arg1)->sbsample);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void D_mad_frame_overlap_set(void * jarg1, void * jarg2) {
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  mad_fixed_t (*arg2)[2][32][18] = (mad_fixed_t (*)[2][32][18]) 0 ;
  
  arg1 = (struct mad_frame *)jarg1;
  arg2 = (mad_fixed_t (*)[2][32][18])jarg2;
  if (arg1) (arg1)->overlap = (mad_fixed_t (*)[2][32][18])arg2;
}


SWIGEXPORT void * D_mad_frame_overlap_get(void * jarg1) {
  void * jresult ;
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  mad_fixed_t (*result)[2][32][18] = 0 ;
  
  arg1 = (struct mad_frame *)jarg1;
  result = (mad_fixed_t (*)[2][32][18]) ((arg1)->overlap);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_mad_frame() {
  void * jresult ;
  struct mad_frame *result = 0 ;
  
  result = (struct mad_frame *)calloc(1, sizeof(struct mad_frame));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_mad_frame(void * jarg1) {
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  
  arg1 = (struct mad_frame *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_mad_header_init(void * jarg1) {
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  
  arg1 = (struct mad_header *)jarg1;
  mad_header_init(arg1);
}


SWIGEXPORT int D_mad_header_decode(void * jarg1, void * jarg2) {
  int jresult ;
  struct mad_header *arg1 = (struct mad_header *) 0 ;
  struct mad_stream *arg2 = (struct mad_stream *) 0 ;
  int result;
  
  arg1 = (struct mad_header *)jarg1;
  arg2 = (struct mad_stream *)jarg2;
  result = (int)mad_header_decode(arg1,arg2);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_frame_init(void * jarg1) {
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  
  arg1 = (struct mad_frame *)jarg1;
  mad_frame_init(arg1);
}


SWIGEXPORT void D_mad_frame_finish(void * jarg1) {
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  
  arg1 = (struct mad_frame *)jarg1;
  mad_frame_finish(arg1);
}


SWIGEXPORT int D_mad_frame_decode(void * jarg1, void * jarg2) {
  int jresult ;
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  struct mad_stream *arg2 = (struct mad_stream *) 0 ;
  int result;
  
  arg1 = (struct mad_frame *)jarg1;
  arg2 = (struct mad_stream *)jarg2;
  result = (int)mad_frame_decode(arg1,arg2);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_frame_mute(void * jarg1) {
  struct mad_frame *arg1 = (struct mad_frame *) 0 ;
  
  arg1 = (struct mad_frame *)jarg1;
  mad_frame_mute(arg1);
}


SWIGEXPORT void D_mad_pcm_samplerate_set(void * jarg1, unsigned int jarg2) {
  struct mad_pcm *arg1 = (struct mad_pcm *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct mad_pcm *)jarg1;
  arg2 = (unsigned int)jarg2;
  if (arg1) (arg1)->samplerate = arg2;
}


SWIGEXPORT unsigned int D_mad_pcm_samplerate_get(void * jarg1) {
  unsigned int jresult ;
  struct mad_pcm *arg1 = (struct mad_pcm *) 0 ;
  unsigned int result;
  
  arg1 = (struct mad_pcm *)jarg1;
  result = (unsigned int) ((arg1)->samplerate);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_pcm_channels_set(void * jarg1, unsigned short jarg2) {
  struct mad_pcm *arg1 = (struct mad_pcm *) 0 ;
  unsigned short arg2 ;
  
  arg1 = (struct mad_pcm *)jarg1;
  arg2 = (unsigned short)jarg2;
  if (arg1) (arg1)->channels = arg2;
}


SWIGEXPORT unsigned short D_mad_pcm_channels_get(void * jarg1) {
  unsigned short jresult ;
  struct mad_pcm *arg1 = (struct mad_pcm *) 0 ;
  unsigned short result;
  
  arg1 = (struct mad_pcm *)jarg1;
  result = (unsigned short) ((arg1)->channels);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_pcm_length_set(void * jarg1, unsigned short jarg2) {
  struct mad_pcm *arg1 = (struct mad_pcm *) 0 ;
  unsigned short arg2 ;
  
  arg1 = (struct mad_pcm *)jarg1;
  arg2 = (unsigned short)jarg2;
  if (arg1) (arg1)->length = arg2;
}


SWIGEXPORT unsigned short D_mad_pcm_length_get(void * jarg1) {
  unsigned short jresult ;
  struct mad_pcm *arg1 = (struct mad_pcm *) 0 ;
  unsigned short result;
  
  arg1 = (struct mad_pcm *)jarg1;
  result = (unsigned short) ((arg1)->length);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_pcm_samples_set(void * jarg1, void * jarg2) {
  struct mad_pcm *arg1 = (struct mad_pcm *) 0 ;
  mad_fixed_t (*arg2)[1152] ;
  
  arg1 = (struct mad_pcm *)jarg1;
  arg2 = (mad_fixed_t (*)[1152])jarg2; 
  {
    mad_fixed_t (*inp)[1152] = (mad_fixed_t (*)[1152])(arg2);
    mad_fixed_t (*dest)[1152] = (mad_fixed_t (*)[1152])(arg1->samples);
    size_t ii = 0;
    for (; ii < 2; ++ii) {
      mad_fixed_t *ip = inp[ii];
      mad_fixed_t *dp = dest[ii];
      size_t jj = 0;
      for (; jj < 1152; ++jj) dp[jj] = ip[jj];
    }
  }
}


SWIGEXPORT void * D_mad_pcm_samples_get(void * jarg1) {
  void * jresult ;
  struct mad_pcm *arg1 = (struct mad_pcm *) 0 ;
  mad_fixed_t (*result)[1152] = 0 ;
  
  arg1 = (struct mad_pcm *)jarg1;
  result = (mad_fixed_t (*)[1152])(mad_fixed_t (*)[1152]) ((arg1)->samples);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * D_new_mad_pcm() {
  void * jresult ;
  struct mad_pcm *result = 0 ;
  
  result = (struct mad_pcm *)calloc(1, sizeof(struct mad_pcm));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_mad_pcm(void * jarg1) {
  struct mad_pcm *arg1 = (struct mad_pcm *) 0 ;
  
  arg1 = (struct mad_pcm *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_mad_synth_filter_set(void * jarg1, void * jarg2) {
  struct mad_synth *arg1 = (struct mad_synth *) 0 ;
  mad_fixed_t (*arg2)[2][2][16][8] ;
  
  arg1 = (struct mad_synth *)jarg1;
  arg2 = (mad_fixed_t (*)[2][2][16][8])jarg2; 
  {
    mad_fixed_t (*inp)[2] = (mad_fixed_t (*)[2])(arg2);
    mad_fixed_t (*dest)[2] = (mad_fixed_t (*)[2])(arg1->filter);
    size_t ii = 0;
    for (; ii < 2; ++ii) {
      mad_fixed_t *ip = inp[ii];
      mad_fixed_t *dp = dest[ii];
      size_t jj = 0;
      for (; jj < 2; ++jj) dp[jj] = ip[jj];
    }
  }
}


SWIGEXPORT void * D_mad_synth_filter_get(void * jarg1) {
  void * jresult ;
  struct mad_synth *arg1 = (struct mad_synth *) 0 ;
  mad_fixed_t (*result)[2][2][16][8] = 0 ;
  
  arg1 = (struct mad_synth *)jarg1;
  result = (mad_fixed_t (*)[2][2][16][8])(mad_fixed_t (*)[2][2][16][8]) ((arg1)->filter);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void D_mad_synth_phase_set(void * jarg1, unsigned int jarg2) {
  struct mad_synth *arg1 = (struct mad_synth *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct mad_synth *)jarg1;
  arg2 = (unsigned int)jarg2;
  if (arg1) (arg1)->phase = arg2;
}


SWIGEXPORT unsigned int D_mad_synth_phase_get(void * jarg1) {
  unsigned int jresult ;
  struct mad_synth *arg1 = (struct mad_synth *) 0 ;
  unsigned int result;
  
  arg1 = (struct mad_synth *)jarg1;
  result = (unsigned int) ((arg1)->phase);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_synth_pcm_set(void * jarg1, void * jarg2) {
  struct mad_synth *arg1 = (struct mad_synth *) 0 ;
  struct mad_pcm *arg2 = (struct mad_pcm *) 0 ;
  
  arg1 = (struct mad_synth *)jarg1;
  arg2 = (struct mad_pcm *)jarg2;
  if (arg1) (arg1)->pcm = *arg2;
}


SWIGEXPORT void * D_mad_synth_pcm_get(void * jarg1) {
  void * jresult ;
  struct mad_synth *arg1 = (struct mad_synth *) 0 ;
  struct mad_pcm *result = 0 ;
  
  arg1 = (struct mad_synth *)jarg1;
  result = (struct mad_pcm *)& ((arg1)->pcm);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_mad_synth() {
  void * jresult ;
  struct mad_synth *result = 0 ;
  
  result = (struct mad_synth *)calloc(1, sizeof(struct mad_synth));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_mad_synth(void * jarg1) {
  struct mad_synth *arg1 = (struct mad_synth *) 0 ;
  
  arg1 = (struct mad_synth *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_mad_synth_init(void * jarg1) {
  struct mad_synth *arg1 = (struct mad_synth *) 0 ;
  
  arg1 = (struct mad_synth *)jarg1;
  mad_synth_init(arg1);
}


SWIGEXPORT void D_mad_synth_mute(void * jarg1) {
  struct mad_synth *arg1 = (struct mad_synth *) 0 ;
  
  arg1 = (struct mad_synth *)jarg1;
  mad_synth_mute(arg1);
}


SWIGEXPORT void D_mad_synth_frame(void * jarg1, void * jarg2) {
  struct mad_synth *arg1 = (struct mad_synth *) 0 ;
  struct mad_frame *arg2 = (struct mad_frame *) 0 ;
  
  arg1 = (struct mad_synth *)jarg1;
  arg2 = (struct mad_frame *)jarg2;
  mad_synth_frame(arg1,(struct mad_frame const *)arg2);
}


SWIGEXPORT void D_mad_decoder_mode_set(void * jarg1, int jarg2) {
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_decoder_mode arg2 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  arg2 = (enum mad_decoder_mode)jarg2; 
  if (arg1) (arg1)->mode = arg2;
}


SWIGEXPORT int D_mad_decoder_mode_get(void * jarg1) {
  int jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_decoder_mode result;
  
  arg1 = (struct mad_decoder *)jarg1;
  result = (enum mad_decoder_mode) ((arg1)->mode);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void D_mad_decoder_options_set(void * jarg1, int jarg2) {
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  int arg2 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->options = arg2;
}


SWIGEXPORT int D_mad_decoder_options_get(void * jarg1) {
  int jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  int result;
  
  arg1 = (struct mad_decoder *)jarg1;
  result = (int) ((arg1)->options);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_mad_decoder_async_get(void * jarg1) {
  void * jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  mad_decoder_async *result = 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  result = (mad_decoder_async *)& ((arg1)->async);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_mad_decoder_sync_get(void * jarg1) {
  void * jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  mad_decoder_sync *result = 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  result = (mad_decoder_sync *) ((arg1)->sync);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_decoder_cb_data_set(void * jarg1, void * jarg2) {
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  arg2 = (void *)jarg2;
  if (arg1) (arg1)->cb_data = arg2;
}


SWIGEXPORT void * D_mad_decoder_cb_data_get(void * jarg1) {
  void * jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  void *result = 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  result = (void *) ((arg1)->cb_data);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_decoder_input_func_set(void * jarg1, void * jarg2) {
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_flow (*arg2)(void *,struct mad_stream *) = (enum mad_flow (*)(void *,struct mad_stream *)) 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  arg2 = (enum mad_flow (*)(void *,struct mad_stream *))jarg2;
  if (arg1) (arg1)->input_func = arg2;
}


SWIGEXPORT void * D_mad_decoder_input_func_get(void * jarg1) {
  void * jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_flow (*result)(void *,struct mad_stream *) = 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  result = (enum mad_flow (*)(void *,struct mad_stream *)) ((arg1)->input_func);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_decoder_header_func_set(void * jarg1, void * jarg2) {
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_flow (*arg2)(void *,struct mad_header const *) = (enum mad_flow (*)(void *,struct mad_header const *)) 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  arg2 = (enum mad_flow (*)(void *,struct mad_header const *))jarg2;
  if (arg1) (arg1)->header_func = arg2;
}


SWIGEXPORT void * D_mad_decoder_header_func_get(void * jarg1) {
  void * jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_flow (*result)(void *,struct mad_header const *) = 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  result = (enum mad_flow (*)(void *,struct mad_header const *)) ((arg1)->header_func);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_decoder_filter_func_set(void * jarg1, void * jarg2) {
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_flow (*arg2)(void *,struct mad_stream const *,struct mad_frame *) = (enum mad_flow (*)(void *,struct mad_stream const *,struct mad_frame *)) 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  arg2 = (enum mad_flow (*)(void *,struct mad_stream const *,struct mad_frame *))jarg2;
  if (arg1) (arg1)->filter_func = arg2;
}


SWIGEXPORT void * D_mad_decoder_filter_func_get(void * jarg1) {
  void * jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_flow (*result)(void *,struct mad_stream const *,struct mad_frame *) = 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  result = (enum mad_flow (*)(void *,struct mad_stream const *,struct mad_frame *)) ((arg1)->filter_func);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_decoder_output_func_set(void * jarg1, void * jarg2) {
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_flow (*arg2)(void *,struct mad_header const *,struct mad_pcm *) = (enum mad_flow (*)(void *,struct mad_header const *,struct mad_pcm *)) 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  arg2 = (enum mad_flow (*)(void *,struct mad_header const *,struct mad_pcm *))jarg2;
  if (arg1) (arg1)->output_func = arg2;
}


SWIGEXPORT void * D_mad_decoder_output_func_get(void * jarg1) {
  void * jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_flow (*result)(void *,struct mad_header const *,struct mad_pcm *) = 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  result = (enum mad_flow (*)(void *,struct mad_header const *,struct mad_pcm *)) ((arg1)->output_func);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_decoder_error_func_set(void * jarg1, void * jarg2) {
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_flow (*arg2)(void *,struct mad_stream *,struct mad_frame *) = (enum mad_flow (*)(void *,struct mad_stream *,struct mad_frame *)) 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  arg2 = (enum mad_flow (*)(void *,struct mad_stream *,struct mad_frame *))jarg2;
  if (arg1) (arg1)->error_func = arg2;
}


SWIGEXPORT void * D_mad_decoder_error_func_get(void * jarg1) {
  void * jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_flow (*result)(void *,struct mad_stream *,struct mad_frame *) = 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  result = (enum mad_flow (*)(void *,struct mad_stream *,struct mad_frame *)) ((arg1)->error_func);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_decoder_message_func_set(void * jarg1, void * jarg2) {
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_flow (*arg2)(void *,void *,unsigned int *) = (enum mad_flow (*)(void *,void *,unsigned int *)) 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  arg2 = (enum mad_flow (*)(void *,void *,unsigned int *))jarg2;
  if (arg1) (arg1)->message_func = arg2;
}


SWIGEXPORT void * D_mad_decoder_message_func_get(void * jarg1) {
  void * jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_flow (*result)(void *,void *,unsigned int *) = 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  result = (enum mad_flow (*)(void *,void *,unsigned int *)) ((arg1)->message_func);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_mad_decoder() {
  void * jresult ;
  struct mad_decoder *result = 0 ;
  
  result = (struct mad_decoder *)calloc(1, sizeof(struct mad_decoder));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_mad_decoder(void * jarg1) {
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_mad_decoder_sync_stream_set(void * jarg1, void * jarg2) {
  mad_decoder_sync *arg1 = (mad_decoder_sync *) 0 ;
  struct mad_stream *arg2 = (struct mad_stream *) 0 ;
  
  arg1 = (mad_decoder_sync *)jarg1;
  arg2 = (struct mad_stream *)jarg2;
  if (arg1) (arg1)->stream = *arg2;
}


SWIGEXPORT void * D_mad_decoder_sync_stream_get(void * jarg1) {
  void * jresult ;
  mad_decoder_sync *arg1 = (mad_decoder_sync *) 0 ;
  struct mad_stream *result = 0 ;
  
  arg1 = (mad_decoder_sync *)jarg1;
  result = (struct mad_stream *)& ((arg1)->stream);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_decoder_sync_frame_set(void * jarg1, void * jarg2) {
  mad_decoder_sync *arg1 = (mad_decoder_sync *) 0 ;
  struct mad_frame *arg2 = (struct mad_frame *) 0 ;
  
  arg1 = (mad_decoder_sync *)jarg1;
  arg2 = (struct mad_frame *)jarg2;
  if (arg1) (arg1)->frame = *arg2;
}


SWIGEXPORT void * D_mad_decoder_sync_frame_get(void * jarg1) {
  void * jresult ;
  mad_decoder_sync *arg1 = (mad_decoder_sync *) 0 ;
  struct mad_frame *result = 0 ;
  
  arg1 = (mad_decoder_sync *)jarg1;
  result = (struct mad_frame *)& ((arg1)->frame);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_mad_decoder_sync_synth_set(void * jarg1, void * jarg2) {
  mad_decoder_sync *arg1 = (mad_decoder_sync *) 0 ;
  struct mad_synth *arg2 = (struct mad_synth *) 0 ;
  
  arg1 = (mad_decoder_sync *)jarg1;
  arg2 = (struct mad_synth *)jarg2;
  if (arg1) (arg1)->synth = *arg2;
}


SWIGEXPORT void * D_mad_decoder_sync_synth_get(void * jarg1) {
  void * jresult ;
  mad_decoder_sync *arg1 = (mad_decoder_sync *) 0 ;
  struct mad_synth *result = 0 ;
  
  arg1 = (mad_decoder_sync *)jarg1;
  result = (struct mad_synth *)& ((arg1)->synth);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_mad_decoder_sync() {
  void * jresult ;
  mad_decoder_sync *result = 0 ;
  
  result = (mad_decoder_sync *)calloc(1, sizeof(mad_decoder_sync));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_mad_decoder_sync(void * jarg1) {
  mad_decoder_sync *arg1 = (mad_decoder_sync *) 0 ;
  
  arg1 = (mad_decoder_sync *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_mad_decoder_async_pid_set(void * jarg1, long jarg2) {
  mad_decoder_async *arg1 = (mad_decoder_async *) 0 ;
  long arg2 ;
  
  arg1 = (mad_decoder_async *)jarg1;
  arg2 = (long)jarg2;
  if (arg1) (arg1)->pid = arg2;
}


SWIGEXPORT long D_mad_decoder_async_pid_get(void * jarg1) {
  long jresult ;
  mad_decoder_async *arg1 = (mad_decoder_async *) 0 ;
  long result;
  
  arg1 = (mad_decoder_async *)jarg1;
  result = (long) ((arg1)->pid);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_decoder_async__in_set(void * jarg1, int jarg2) {
  mad_decoder_async *arg1 = (mad_decoder_async *) 0 ;
  int arg2 ;
  
  arg1 = (mad_decoder_async *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->in = arg2;
}


SWIGEXPORT int D_mad_decoder_async__in_get(void * jarg1) {
  int jresult ;
  mad_decoder_async *arg1 = (mad_decoder_async *) 0 ;
  int result;
  
  arg1 = (mad_decoder_async *)jarg1;
  result = (int) ((arg1)->in);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_mad_decoder_async__out_set(void * jarg1, int jarg2) {
  mad_decoder_async *arg1 = (mad_decoder_async *) 0 ;
  int arg2 ;
  
  arg1 = (mad_decoder_async *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->out = arg2;
}


SWIGEXPORT int D_mad_decoder_async__out_get(void * jarg1) {
  int jresult ;
  mad_decoder_async *arg1 = (mad_decoder_async *) 0 ;
  int result;
  
  arg1 = (mad_decoder_async *)jarg1;
  result = (int) ((arg1)->out);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_mad_decoder_async() {
  void * jresult ;
  mad_decoder_async *result = 0 ;
  
  result = (mad_decoder_async *)calloc(1, sizeof(mad_decoder_async));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_mad_decoder_async(void * jarg1) {
  mad_decoder_async *arg1 = (mad_decoder_async *) 0 ;
  
  arg1 = (mad_decoder_async *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_mad_decoder_init(void * jarg1, void * jarg2, void * jarg3, void * jarg4, void * jarg5, void * jarg6, void * jarg7, void * jarg8) {
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  void *arg2 = (void *) 0 ;
  enum mad_flow (*arg3)(void *,struct mad_stream *) = (enum mad_flow (*)(void *,struct mad_stream *)) 0 ;
  enum mad_flow (*arg4)(void *,struct mad_header const *) = (enum mad_flow (*)(void *,struct mad_header const *)) 0 ;
  enum mad_flow (*arg5)(void *,struct mad_stream const *,struct mad_frame *) = (enum mad_flow (*)(void *,struct mad_stream const *,struct mad_frame *)) 0 ;
  enum mad_flow (*arg6)(void *,struct mad_header const *,struct mad_pcm *) = (enum mad_flow (*)(void *,struct mad_header const *,struct mad_pcm *)) 0 ;
  enum mad_flow (*arg7)(void *,struct mad_stream *,struct mad_frame *) = (enum mad_flow (*)(void *,struct mad_stream *,struct mad_frame *)) 0 ;
  enum mad_flow (*arg8)(void *,void *,unsigned int *) = (enum mad_flow (*)(void *,void *,unsigned int *)) 0 ;
  
  arg1 = (struct mad_decoder *)jarg1;
  arg2 = (void *)jarg2;
  arg3 = (enum mad_flow (*)(void *,struct mad_stream *))jarg3;
  arg4 = (enum mad_flow (*)(void *,struct mad_header const *))jarg4;
  arg5 = (enum mad_flow (*)(void *,struct mad_stream const *,struct mad_frame *))jarg5;
  arg6 = (enum mad_flow (*)(void *,struct mad_header const *,struct mad_pcm *))jarg6;
  arg7 = (enum mad_flow (*)(void *,struct mad_stream *,struct mad_frame *))jarg7;
  arg8 = (enum mad_flow (*)(void *,void *,unsigned int *))jarg8;
  mad_decoder_init(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
}


SWIGEXPORT int D_mad_decoder_finish(void * jarg1) {
  int jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  int result;
  
  arg1 = (struct mad_decoder *)jarg1;
  result = (int)mad_decoder_finish(arg1);
  jresult = result;
  return jresult;
}


SWIGEXPORT int D_mad_decoder_run(void * jarg1, int jarg2) {
  int jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  enum mad_decoder_mode arg2 ;
  int result;
  
  arg1 = (struct mad_decoder *)jarg1;
  arg2 = (enum mad_decoder_mode)jarg2; 
  result = (int)mad_decoder_run(arg1,arg2);
  jresult = result;
  return jresult;
}


SWIGEXPORT int D_mad_decoder_message(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  struct mad_decoder *arg1 = (struct mad_decoder *) 0 ;
  void *arg2 = (void *) 0 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  int result;
  
  arg1 = (struct mad_decoder *)jarg1;
  arg2 = (void *)jarg2;
  arg3 = (unsigned int *)jarg3;
  result = (int)mad_decoder_message(arg1,arg2,arg3);
  jresult = result;
  return jresult;
}


#ifdef __cplusplus
}
#endif

