
#ifndef SPI_PROTOCOLS_SOLENOIDS_H
#define SPI_PROTOCOLS_SOLENOIDS_H

// SPI protocol indices
#define SPI_SOLENOIDS_FLIPPER_LEFT_IDX       0
#define SPI_SOLENOIDS_FLIPPER_RIGHT_IDX      1

#define SPI_SOLENOIDS_DROP_TARGET_BANK_0_IDX 2

#define SPI_SOLENOIDS_SLINGSHOT_LEFT_IDX       3
#define SPI_SOLENOIDS_SLINGSHOT_RIGHT_IDX      4

#define SPI_SOLENOIDS_BUMPER_0_IDX       5
#define SPI_SOLENOIDS_BUMPER_1_IDX       6
#define SPI_SOLENOIDS_BUMPER_2_IDX       7

#define SPI_SOLENOIDS_BALL_RETURN_IDX 8

#define SPI_SOLENOIDS_AUX_0_IDX 9
#define SPI_SOLENOIDS_AUX_1_IDX 10

#endif // SPI_PROTOCOLS_SOLENOIDS_H

