
#ifndef SPI_PROTOCOLS_SOLENOIDS_H
#define SPI_PROTOCOLS_SOLENOIDS_H

// SPI protocol indices
#define SPI_SOLENOIDS_FLIPPER_LEFT_IDX       0
#define SPI_SOLENOIDS_FLIPPER_RIGHT_IDX      1

#define SPI_SOLENOIDS_DROP_TARGET_BANK_0_IDX 2

#endif // SPI_PROTOCOLS_SOLENOIDS_H

