
#ifndef SPI_PROTOCOLS_SWITCHES_H
#define SPI_PROTOCOLS_switches_H

#define SPI_SWITCHES_FLIPPER_LEFT_IDX        2
#define SPI_SWITCHES_FLIPPER_RIGHT_IDX       5

#define SPI_SWITCHES_DROP_TARGET_BANK_0_IDX 16

#endif // SPI_PROTOCOLS_SWITCHES_H

